/*
 * This file is generated by jOOQ.
 */
package com.xzh.springjooq.db;


import com.xzh.springjooq.db.tables.SysUser;

import javax.annotation.Generated;


/**
 * Convenience access to all tables in test_db
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.11"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * 系统用户
     */
    public static final SysUser SYS_USER = com.xzh.springjooq.db.tables.SysUser.SYS_USER;
}
