/*
 * This file is generated by jOOQ.
 */
package com.xzh.springjooq.db;


import com.xzh.springjooq.db.tables.SysUser;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.11"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TestDb extends SchemaImpl {

    private static final long serialVersionUID = -1662016179;

    /**
     * The reference instance of <code>test_db</code>
     */
    public static final TestDb TEST_DB = new TestDb();

    /**
     * 系统用户
     */
    public final SysUser SYS_USER = com.xzh.springjooq.db.tables.SysUser.SYS_USER;

    /**
     * No further instances allowed
     */
    private TestDb() {
        super("test_db", null);
    }


    /**
     * {@inheritDoc}
     */
    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        List result = new ArrayList();
        result.addAll(getTables0());
        return result;
    }

    private final List<Table<?>> getTables0() {
        return Arrays.<Table<?>>asList(
            SysUser.SYS_USER);
    }
}
